import { Amplify } from 'aws-amplify';

// amplify_outputs.json is auto-generated by `amplify sandbox` or CI/CD
// In dev, run `npx ampx sandbox` first to generate this file
let outputs: Record<string, unknown> = {};

try {
  // Dynamic import so build doesn't fail if file doesn't exist yet
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod = await import('../../amplify_outputs.json');
  outputs = mod.default;
} catch {
  console.warn('[Amplify] amplify_outputs.json not found — run `npx ampx sandbox` to generate it.');
}

Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);

export {};
